ctfs/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('<str:cat_slug>/', views.category, name='category'),
        path('<str:cat_slug>/<str:ctf_slug>', views.ctf, name='ctf')
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('ctfs/', include('ctfs.urls')),
    path('accounts/', include('accounts.urls')),
    path('scoreboard/', include('scoreboard.urls')),
    path('dashboard/secret/admin', admin.site.urls),
]

ctfs/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name        =   models.CharField(max_length=200)
    description =   models.TextField()
    slug        =   models.SlugField(max_length=55)
    def __str__(self):
        return self.name

class CTF(models.Model):
    name        =   models.CharField(max_length=200)
    flag        =   models.CharField(max_length=100)
    description =   models.TextField(blank=True)
    file        =   models.FileField(blank=True, upload_to='challenges')
    ctf_url     =   models.URLField(blank=True)
    points      =   models.PositiveSmallIntegerField()
    slug        =   models.SlugField(max_length=55)
    pub_date    =   models.DateTimeField('Date published')
    category    =   models.ForeignKey(
                                       Category,
                                       on_delete=models.SET_NULL,
                                       null=True,
                                       )
    author        =   models.ForeignKey(User, unique=False, on_delete=models.CASCADE) 
    def solved_by(self, user):
        """True if the exercise has been solved by the user."""
        if not user.is_authenticated:
            return False
        try:
            CTF_flags.objects.get(user=user, ctf=self)
            return True
        except CTF_flags.DoesNotExist:
            return False
    
    def __str__(self):
        return self.name

class CTF_flags(models.Model):
    user        =   models.ForeignKey(User, unique=False, on_delete=models.CASCADE) 
    ctf         =   models.ForeignKey(CTF, unique=False, on_delete=models.CASCADE)
    flag_date   =   models.DateTimeField('Flag date')
    
    class Meta:
        ordering = ['-flag_date']
        verbose_name = 'solution'
        verbose_name_plural = 'solutions'
# Create your models here.

ctfs/forms.py
from django import forms

class submit_flag(forms.Form):
    flag    =   forms.CharField(label="Flag", max_length=100)

ctfs/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.models import timezone
from .models import Category, CTF, CTF_flags
from .forms import submit_flag
from accounts.models import UserProfileInfo

def category(request, cat_slug):
    cat         =   get_object_or_404(Category, slug=cat_slug)
    ctfs        =   CTF.objects.filter(category=cat).order_by('-points')
    for ex in ctfs:
        ex.solved_num  =   CTF_flags.objects.filter(ctf=ex).count()
        ex.solved = ex.solved_by(request.user)
    return render(request, 'ctfs/ctfs_list.html', {'ctfs' : ctfs, 'cat' : cat})

def ctf(request, cat_slug, ctf_slug):
    ctf_info    =   get_object_or_404(CTF, slug=ctf_slug)
    flagged     =   False
    solved_list =   CTF_flags.objects.filter(ctf=ctf_info).order_by('flag_date')
    if request.user.is_authenticated:
        if CTF_flags.objects.filter(user=request.user, ctf=ctf_info):
            flagged = True
    if request.method == 'POST':
        if request.user.is_authenticated:
            form = submit_flag(data=request.POST)
            if flagged == False and form.is_valid():
                if CTF.objects.filter(flag=request.POST.get('flag'), slug=ctf_slug):
                    new =   CTF_flags(user = request.user, ctf = ctf_info, flag_date = timezone.now())
                    new.save()
                    profil = UserProfileInfo.objects.get(user=request.user)
                    profil.last_submission_date = timezone.now()
                    profil.score += ctf_info.points
                    profil.save()
                    return render(request, 'ctfs/ctf_info.html', {'form' : form, 'ctf' : ctf_info, 'solved_list': solved_list, 'valitated': True})
                else:
                    return render(request, 'ctfs/ctf_info.html', {'form' : form, 'ctf' : ctf_info, 'solved_list': solved_list, 'failed': True})
            else:
                form = submit_flag()
                return render(request, 'ctfs/ctf_info.html', {'form' : form, 'ctf' : ctf_info, 'solved_list': solved_list, 'alvalitated': True})
        else:
            form = submit_flag()
            return render(request, 'ctfs/ctf_info.html', {'form' : form, 'ctf' : ctf_info, 'solved_list': solved_list})
    else:
        form = submit_flag()
        return render(request, 'ctfs/ctf_info.html', {'form' : form, 'ctf' : ctf_info, 'solved_list': solved_list, 'alvalitated': flagged})

   
# Create your views here.

ctfs/templates/ctfs/ctf_info.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
  <div class="col-sm-12 col-md-9">
    <div class="ctf-block">
      <div class="ctf-head">
        <h3>{{ ctf.name }}</h3>
        <small>Published {{ ctf.pub_date }}</small>
      </div>
      <div class="ctf-body">
        {{ ctf.description|safe }}
      </div>
      <div class="ctf-footer">
              {% if request.user.is_authenticated %}
              {% if valitated == True %}
                <p>Congratulation !</p>
              {% elif alvalitated == True %}
                <p>Already flagged</p>
              {% else %}
              {% if failed %}
              <p>Wrong flag ! You can do it !</p>
              {% endif %}
              {% if ctf.ctf_url %}
              <a class="begin-ctf-link" target="_blank" href="{{ ctf.ctf_url }}">Start the challenge</a></br>
              {% elif ctf.file %}
              <a class="begin-ctf-link" target="_blank" href="{{ ctf.file.url }}">Download</a></br>
              {% endif %}
              <form method="post" class="submitflag-form">
                      {% csrf_token %}
                      <input type="text" name="flag" maxlength="48" required="" id="id_flag">
                      <input class="form-control" type="submit" value=">">
              </form>

              {% endif %}
              {% endif %}
      </div>
    </div>
    <div>
      <h4>Solved by</h4>
			{% if solved_list %}
			<table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">Pseudo</th>
            <th scope="col">Website</th>
            <th scope="col">Points</th>
            <th scope="col">Date</th>
          </tr>
        </thead>
        <tbody>
					{% for s in solved_list %}
					<tr>
							<th scope="row">{{ s.user.username }}</th>
							<td>{{ s.user.userprofileinfo.portfolio_site }}</td>
							<td>{{ s.user.userprofileinfo.points }}</td>
							<td>{{ s.flag_date }}</td>
          </tr>
					{% endfor %}
        </tbody>
      </table>
			{% else %}
				<p>Nobody have solved this CTF.</p>
			{% endif %}
    </div>
  </div>
  <div class="d-none d-md-block col-10 col-md-3 right-sidebar">
    <ul class="list-group">
	    <li class="list-group-item">Author: {{ ctf.author.username }}</li>
      <li class="list-group-item">Points: {{ ctf.points }}</li>
		
		</ul>
  </div>
</div>
{% endblock %}

ctfs/templates/ctfs/ctfs_list.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
  <div class="col-sm-12 col-md-9 news-card">
      <h3>{{ cat.name }}</h3>
  {% if ctfs %}
  <table class="table table-striped table-dark">
      <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Name</th>
        <th scope="col">Points</th>
        <th scope="col">Solved</th>
      </tr>
    </thead>
    <tbody>
      {% for ctf in ctfs %}
      <tr>
        {% if request.user.is_authenticated %}
                {% if ctf.solved %}
                        <th scope="row" style="color:green;">&#10003;</th>
                {% else %}
                        <th scope="row" style="color:red;">&#10005;</th>
                {% endif %}
        {% else %}
                <th scope="row"> </th>
        {% endif %}
        <td><a href="/ctfs/{{ cat.slug }}/{{ ctf.slug }}">{{ ctf.name }}</td>
        <td>{{ ctf.points }}</td>
        <td>{{ ctf.solved_num }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p>No ctf available for this category.</p>
  {% endif %}
  </div>
  <div class="col-sm-12 col-md-3 right-sidebar">
    <ul class="list-group">
    <li class="list-group-item active">Categories</li>
    {% if cats %}
    {% for c in cats %}
    <a class="list-group-item" href="/ctfs/{{ c.slug }}">{{ c.name }}</a>
    {% endfor %}
    {% else %}
    <li class="list-group-item">No category available.</li>
    {% endif %}
    </ul>
  </div>
</div>
{% endblock %}