accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
        path('signin/', views.signin, name='signin'),
        path('signup/', views.signup, name='signup'),
        path('profile/<str:user_name>', views.profile, name='profile'),
        path('account/', views.account, name='account'),
        path('logout/', views.out, name='out')
]

ctfs/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('<str:cat_slug>/', views.category, name='category'),
        path('<str:cat_slug>/<str:ctf_slug>', views.ctf, name='ctf')
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('ctfs/', include('ctfs.urls')),
    path('accounts/', include('accounts.urls')),
    path('scoreboard/', include('scoreboard.urls')),
    path('dashboard/secret/admin', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.contrib.auth import models as auth_models
from django.contrib.auth.models import timezone
from django.db.models import F, Min, Max

# Create your models here
class UserProfileInfo(models.Model):
    user                    =   models.OneToOneField(auth_models.User, on_delete=models.CASCADE)
    portfolio_site          =   models.URLField(blank=True)
    score                   =   models.PositiveIntegerField(default=0, db_index=True)
    last_submission_date    =   models.DateTimeField('Last Submission Date', default=timezone.now)
    def __str__(self):
        return self.user.username
    class Meta:
        ordering = ['-score', 'last_submission_date', 'user__username']
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

# Create your models here.

accounts/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site',)

accounts/views.py
from django.shortcuts import render
from django import forms
from .forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

def signin(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('home'))
                else:
                    return HttpResponse("Your account was inactive.")
            else:
                return render(request, 'accounts/login.html', {'error': True})
        else:
            return render(request, 'accounts/login.html', {})
    else:
        return HttpResponseRedirect(reverse('home'))

def signup(request):
    if not request.user.is_authenticated:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
        registered = False
        if request.method == 'POST':
            pass1 = request.POST.get('password')
            if len(pass1) < 8:
                return render(request,'accounts/register.html', {'user_form':user_form, 'profile_form':profile_form, 'registered_failed':"The new password must be at least %d characters long." % 8})
            first_isalpha = pass1[0].isalpha()
            if not any(c.isdigit() for c in pass1) or not any(c.isalpha() for c in pass1):
                return render(request,'accounts/register.html', {'user_form':user_form, 'profile_form':profile_form, 'registered_failed':"The password must contain at least one letter and at least one digit or punctuation character."})
            if User.objects.filter(email=request.POST.get('email')).exists():
                return render(request,'accounts/register.html', {'user_form':user_form, 'profile_form':profile_form, 'registered_failed':"A user with that email already exists."})
            user_form = UserForm(data=request.POST)
            profile_form = UserProfileInfoForm(data=request.POST)
            if user_form.is_valid() and profile_form.is_valid():
                user = user_form.save()
                user.set_password(user.password)
                user.save()
                profile = profile_form.save(commit=False)
                profile.user = user
                profile.save()
                registered = True
            else:
                return render(request,'accounts/register.html', {'user_form':user_form, 'profile_form':profile_form, 'registered_failed':"A user with that username already exists."})
        return render(request,'accounts/register.html',
                {'user_form':user_form,
                    'profile_form':profile_form,
                    'registered':registered})
    else:
        return HttpResponseRedirect(reverse('home'))

@login_required
def out(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

@login_required
def account(request):
    pass

@login_required
def profile(request):
    pass

# Create your views here.

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
        <div class="col-sm-12 col-md-9">
                <div class="ctf-block">
                        <div class="ctf-head">
                                <h3>Login</h3>
                        </div>
                        <div class="ctf-body">
                            <div class="col-sm-8 col-md-6 mx-auto">
                                    {% if error %}
                                    <p>Please, verify your infos.</p>
                                    {% endif %}
                                    <form method="post">
                                            {% csrf_token %}
                                                <div class="form-group">
                                            <input class="form-control" type="text" name="username" placeholder="Username"></br>
                                            <input class="form-control" type="password" name="password" placeholder="Password"></br>
                                            <input class="form-control" type="submit" value="login">
                                        </div>
                                    </form>
                            </div>
                        </div>
                </div>

        </div>
        <div class="col-sm-12 col-md-3 right-sidebar">
                <ul class="list-group">
                        <a href="/accounts/signin" class="list-group-item">Login</a>
                        <a href="/accounts/signup" class="list-group-item">Sign up</a>
                </ul>
        </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
        <div class="col-sm-12 col-md-9">
                <div class="ctf-block">
                        <div class="ctf-head">
                                <h3>Register</h3>
                        </div>
                        <div class="ctf-body sign-body">
                            <div class="col-sm-8 col-md-6 mx-auto">
                                {% if registered %}
                                <h1>Welcome !</h1>
                                {% else %}
                                {% if registered_failed %}
                                        <span>{{ registered_failed }}</span>
                                {% endif %}
                                <form enctype="multipart/form-data" method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                        <input class="form-control" type="text" name="username" placeholder="Username*" maxlength="150" required="" id="id_username"></br>
                                        <input class="form-control" type="password" name="password" placeholder="Password*" required="" id="id_password"></br>
                                        <input class="form-control" type="email" name="email" placeholder="pleasedontgivemy@private.infos*" required="" maxlength="254" id="id_email"></br>
                                        <input class="form-control" type="url" name="portfolio_site" placeholder="Personal website"maxlength="200" id="id_portfolio_site"></br>
                                        <input type="submit" name="" class="form-control" value="Register">
                                        </div>
                                </form>
                                {% endif %}
                            </div>
                        </div>
                </div>

        </div>
        <div class="col-sm-12 col-md-3 right-sidebar">
                <ul class="list-group">
                        <a href="/accounts/signup" class="list-group-item">Sign up</a>
                        <a href="/accounts/signin" class="list-group-item">Login</a>
                </ul>
        </div>
</div>
{% endblock %}